#!/usr/bin/env bash
# Installs nginx web server on ubuntu 16.04
sudo apt-get -y update
sudo apt-get -y install nginx
# Adjust the Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Index file & Start Nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
