#!/usr/bin/env bash
# Installs nginx web server on ubuntu 16.04
sudo apt update
sudo apt-get -y install nginx
# Adjust the Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Index file
echo "Holberton School" > /var/www/html/index.html
# Start Nginx
sudo service nginx start
