#!/usr/bin/env bash
# Install and configure HAproxy on the lb-01 server
# Install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
# Enable haproxy to start at boot
sudo echo "ENABLED=1" >> /etc/default/haproxy
# Set up the HAproxy
sudo echo "
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
backend web-backend
	balance roundrobin
	server 1456-web-01 34.74.148.216:80 check
	server 1456-web-02 52.91.39.101:80 check
" >> /etc/haproxy/haproxy.cfg
# Restart the haproxy
sudo service haproxy restart
