#!/usr/bin/env bash
# Write a Bash script that:
    # Creates the file /var/run/holbertonscript.pid containing its PID
    # Displays To infinity and beyond indefinitely
    # Displays I hate the kill command when receiving a SIGTERM signal
    # Displays Y U no love me?! when receiving a SIGINT signal
    # Deletes the file /var/run/holbertonscript.pid and terminates itself
    #+ when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; sudo rm /var/run/holbertonscript.pid; exit" 15
trap "echo 'Y U no love me?!'" 2
trap "sudo rm /var/run/holbertonscript.pid; exit" 3
while :
do
    echo 'To infinity and beyond'
    sleep 2
done
