#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# only username, user id, Home directory path for the user
while IFS=: read -r line
do
	echo "$line" | cut -f1,3,6 -d:
done < /etc/passwd
