#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes.
i=0
j=1
while [ $i -le 12 ]; do
	echo "Hour:" $i
	(( i++ ))
	while [ $j -le 59 ]; do
		echo $j
		(( j++ ))
	done
	j=1
done
