#!/usr/bin/env bash
# Script that gives you information about the holbertonschool file.
# if the file exists, does not exist, file exists, file is empty, holbertonschool file is empty.
# file is not empty, file is a regular file, file is not a regular file.
FILE="holbertonschool"
if [ -e "$FILE" ]; then
	echo "$FILE file exists"
	if [ -s "$FILE" ]; then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	if [ -f "$FILE" ]; then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi
